parent_variant: v101
model_family: dense_bow
automl:
  max_trials: 3
  seed: 42
training:
  epochs: 3
  batch_size: 64
  learning_rate: 0.001
  max_samples: null
imbalance:
  strategy: rare_events
  max_majority_samples: 20000
evaluation:
  split:
    train: 0.7
    val: 0.15
    test: 0.15
metrics:
  primary: recall
  metric_mode: max
  report:
  - precision
  - f1
  - confusion_matrix
search_space:
  common:
    learning_rate:
    - 0.001
    - 0.0005
    batch_size:
    - 32
    - 64
    dropout:
    - 0.0
    - 0.2
  dense_bow:
    n_layers:
    - 1
    - 2
    units:
    - 32
    - 64
  sequence_embedding:
    embed_dim:
    - 8
    - 16
    n_layers:
    - 1
    - 2
    units:
    - 32
    - 64
  cnn1d:
    embed_dim:
    - 8
    - 16
    filters:
    - 16
    - 32
    kernel_size:
    - 3
    - 5
    n_layers:
    - 1
    units:
    - 32
    - 64
