stages:
  01_explore:
    cmd: python scripts/01_explore/01_explore.py
    deps:
      - scripts/01_explore/01_explore.py
      - params/01_explore/base_params.yaml
    
  02_prepareeventsds:
    cmd: python scripts/02_prepareeventsds/02_run_prepareeventsds.py
    deps:
      - scripts/02_prepareeventsds/02_run_prepareeventsds.py
      - params/02_prepareeventsds/base_params.yaml

  03_preparewindowsds:
    cmd: python scripts/03_preparewindowsds/03_preparewindowsds.py
    deps:
      - scripts/03_preparewindowsds/03_preparewindowsds.py
      - params/03_preparewindowsds/base_params.yaml
