prediction_objective:
  operator: OR
  events:
  - Battery_Active_Power_Set_Response_0_40-to-80_100
  - Battery_Active_Power_Set_Response_40_60-to-80_100
  - Battery_Active_Power_Set_Response_60_80-to-80_100
parent_variant: v301
prediction_name: Battery_Active_Power_Set_Response_any-to-80_100
