# ============================================================
# FASE 05 — MODELING
# Parámetros base por defecto
# ============================================================
# Variante F05 produce:
# - 1 único modelo seleccionado por métrica primaria
# - dataset de entrenamiento congelado
# - reporte de experimentos internos
# ============================================================

# ------------------------------------------------------------
# Linaje
# ------------------------------------------------------------
parent_variant: null        # vNNN (variante de F04) — OBLIGATORIO
model_family: null          # sequence_embedding | dense_bow | cnn1d — OBLIGATORIO

# ------------------------------------------------------------
# AutoML (ligero y reproducible)
# ------------------------------------------------------------
automl:
  max_trials: 3             # número máximo de configuraciones a probar
  seed: 42                  # semilla global

# ------------------------------------------------------------
# Entrenamiento (valores fijos)
# ------------------------------------------------------------
training:
  epochs: 3
  batch_size: 64
  learning_rate: 0.001
  # Si strategy=rare_events, max_samples se ignora
  max_samples: null

# ------------------------------------------------------------
# Manejo de desbalanceo
# ------------------------------------------------------------
imbalance:
  # Estrategias:
  # - none
  # - rare_events
  strategy: none
  # Solo aplica si strategy=rare_events
  max_majority_samples: null

# ------------------------------------------------------------
# Evaluación
# ------------------------------------------------------------
evaluation:
  split:
    train: 0.7
    val: 0.15
    test: 0.15

# ------------------------------------------------------------
# Métricas
# ------------------------------------------------------------
metrics:
  primary: recall           # métrica usada para selección
  metric_mode: max            # 'max' si se busca maximizar, 'min' si minimizar
  report:
    - precision
    - f1
    - confusion_matrix

# ------------------------------------------------------------
# Espacios de búsqueda por familia
# (solo hiperparámetros explorados)
# ------------------------------------------------------------
search_space:

  common:
    learning_rate: [0.001, 0.0005]
    batch_size: [32, 64]
    dropout: [0.0, 0.2]

  dense_bow:
    n_layers: [1, 2]
    units: [32, 64]

  sequence_embedding:
    embed_dim: [8, 16]
    n_layers: [1, 2]
    units: [32, 64]

  cnn1d:
    embed_dim: [8, 16]
    filters: [16, 32]
    kernel_size: [3, 5]
    n_layers: [1]
    units: [32, 64]

