# ============================================================
# FASE 07 — DEPLOY & RUNTIME VALIDATION
# ============================================================

# Variante F06 que se va a ejecutar
parent_variant_f06: null   # vNNN obligatorio

# ------------------------------------------------------------
# Runtime
# ------------------------------------------------------------

runtime:
  host: "127.0.0.1"
  port: 5005

batch_size: 256
